/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import configDB.jabatan;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class frameJabatan extends javax.swing.JFrame {
    
    private jabatan tbljabatan;

    /**
     * Creates new form frameJabatan
     */
    public frameJabatan() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbljabatan = new jabatan();
        tbljabatan.tampilDataAnggota(tableJabatan, "SELECT * FROM jabatan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMasaKerjaBulan = new javax.swing.JTextField();
        txtMasaKerjaTahun = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        txtNip = new javax.swing.JTextField();
        txtIdJabatan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJabatan = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jabatan");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("ID Jabatan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("NIP");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Jabatan");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Masa Kerja Bulan");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Masa Kerja Tahun");

        txtMasaKerjaBulan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMasaKerjaBulan.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtMasaKerjaTahun.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtMasaKerjaTahun.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtJabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtJabatan.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtNip.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtNip.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtIdJabatan.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtIdJabatan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdJabatanActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tableJabatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableJabatan);

        txtCari.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        btnCetak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCetak.setText("Cetak Laporan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(txtJabatan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMasaKerjaTahun, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMasaKerjaBulan)
                                    .addComponent(txtIdJabatan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnCetak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMasaKerjaTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMasaKerjaBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdJabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdJabatanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    try {
        if (txtIdJabatan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "ID Jabatan Belum diisi");
            txtIdJabatan.requestFocus();
        } else if (txtNip.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "NIP Belum Diisi");
            txtNip.requestFocus();
        }else if (txtJabatan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jabatan Belum Diisi");
            txtJabatan.requestFocus();
        }else if (txtMasaKerjaTahun.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masa Kerja Tahun Belum Diisi");
            txtMasaKerjaTahun.requestFocus();
        }else if (txtMasaKerjaBulan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Masa Kerja Bulan Belum Diisi");
            txtMasaKerjaBulan.requestFocus();
        }else {
            // 🔹 Tambahkan log agar tahu event dijalankan
            System.out.println("Tombol Tambah Ditekan");

            // 🔹 Panggil fungsi simpan (tidak ubah strukturnya)
            tbljabatan.SimpanAnggota(
                Integer.parseInt(txtIdJabatan.getText()),
                Integer.parseInt(txtNip.getText()),
                txtJabatan.getText(),
                txtMasaKerjaTahun.getText(),
                txtMasaKerjaBulan.getText()
            );
            tbljabatan.tampilDataAnggota(tableJabatan, "SELECT * FROM jabatan");

            // 🔹 Tambahkan indikator berhasil
            if (tbljabatan.validasi == true){
                JOptionPane.showMessageDialog(null, "ID sudah terdaftar! Data tidak disimpan.");
                txtIdJabatan.setText(String.valueOf(tbljabatan.VAR_idjabatan));
                txtNip.setText(String.valueOf(tbljabatan.VAR_nip));
                txtJabatan.setText(tbljabatan.VAR_jabatan);
                txtMasaKerjaTahun.setText(tbljabatan.VAR_masakerjatahun);
                txtMasaKerjaBulan.setText(tbljabatan.VAR_masakerjabulan);
            } else {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan ke database!");
            }
            }   
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace(); // tampilkan detail di console
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:\
    try {
            tbljabatan.ubahAnggota(Integer.parseInt(txtIdJabatan.getText()), Integer.parseInt(txtNip.getText()), txtJabatan.getText(), txtMasaKerjaTahun.getText(), txtMasaKerjaBulan.getText());
    } catch (Exception e) {
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    try {
        if (txtIdJabatan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID Jabatan yang ingin dihapus!");
            return;
        }

        int id = Integer.parseInt(txtIdJabatan.getText());
        tbljabatan.hapusAnggota01(id);

        // Kosongkan textfield setelah data berhasil dihapus
        txtIdJabatan.setText(null);
        txtNip.setText(null);
        txtJabatan.setText(null);
        txtMasaKerjaTahun.setText(null);
        txtMasaKerjaBulan.setText(null);
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID Jabatan harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    String cari = "select * from jabatan where nip like '%"+txtCari.getText()+"%'"
                + "OR jabatan like '%"+txtCari.getText()+"%' ";
    tbljabatan.tampilDataAnggota(tableJabatan, cari);
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
    String cari = "select * from jabatan where nip like '%"+txtCari.getText()+"%'"
                + "OR jabatan like '%"+txtCari.getText()+"%' ";
    tbljabatan.tampilDataAnggota(tableJabatan, cari);
    }//GEN-LAST:event_txtCariKeyPressed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        tbljabatan.cetakLaporan("src/laporan/laporanJabatan.jrxml", "SELECT * FROM jabatan");
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameJabatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameJabatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJabatan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdJabatan;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtMasaKerjaBulan;
    private javax.swing.JTextField txtMasaKerjaTahun;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables
}
